### PR TITLE
Rename widget methods to use prefix rsc_

### PR DESCRIPTION
**Pull request by marcosnav**
Rename all widget methods to use prefix `rsc_`

### CODE REVIEW

**Review by Lytol — APPROVED** [review]
That's a lot of renames :-P  All good as long as `check()` passes.

**Review by edavidaja — CHANGES_REQUESTED** [review]
The mixed case on the shiny bindings 🙈 
Does each component actually require its own named binding? if we could unify them under `renderConnectwidget` / `connectwidgetOutput` that might be a bit better?

**Comment by marcosnav** [comment]
@edavidaja yeah, the mixed naming wasn't necessary, updated 👍

**Review by edavidaja — APPROVED** [review]
👍🏾

**Pull request merged**
