### PR TITLE
Responsive Grid & Cards

### PR DESCRIPTION
**Pull request by marcosnav**
PR introducing responsive design for grid and cards.

**Grid**
resp-grid

**Card**
card-resp

### CODE REVIEW

**Review by Lytol — COMMENTED** [review]
Since we're already using Bootstrap, any reason not to use the built-in Bootstrap responsive grid/utilities/variables?

**Comment by marcosnav** [comment]
@Lytol yeah, I thought about it, but at the end that would introduce more (unnecessary IMO) complexity in the components, even more on the grid view.

Since, bootstrap handles grids with markup in the form `.container > .row > .col(s)...` the component would need to computate how many `div.row`s with how many `col`s each one (or computate when to insert a `div.w-100`), every time the user paginates, filters, searches and/or resizes. Something that can be achived with only CSS and flexbox.

However, what I just noticed is that I could make use of bootstrap's `media-breakpoint...` mixins instead of raw media queries :thinking:, I'll try that.

**Comment by Lytol** [comment]
All fair, you do whatever you think is best.

**Review by edavidaja — APPROVED** [review]
👍🏾

**Pull request merged**
