### PR TITLE
Fix for widgets not accepting crosstalk shared object

### PR DESCRIPTION
**Pull request by marcosnav**

### CODE REVIEW

**Review by edavidaja — COMMENTED** [review]
This is the example from the crosstalk vignette--I'll work on a more minimal example but this throws a `Uncaught TypeError: Cannot read property 'split' of undefined` at the JS console for me.

````
---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
library(connectwidgets)
library(dplyr)
library(htmltools)
library(purrr)

knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)

client <- connect(
  # server  = Sys.getenv("CONNECT_SERVER"),
  # api_key = Sys.getenv("CONNECT_API_KEY")
  )

all_content <- client %>%
  content()

some_content <- slice_sample(all_content, prop = .1)
```

![](https://source.unsplash.com/1920x1080/?forest "A random forest.")

## Components

### card

```{r card}
some_content_xfilter <- crosstalk::SharedData$new(
  some_content,
  ~ guid,
  group = "xfilter"
  )

rsc_content_filtered_shared <-
  some_content %>%
  group_nest(owner_username, .key = "content_df", keep = TRUE)

div(
  h3("Grouped Grids by Owner", class = "text-center"),
  rsc_filter(some_content_xfilter),
  pmap(
    rsc_content_filtered_shared,
    {
      ~ tagList(
        h4(..1),
        rsc_grid(crosstalk::SharedData$new(..2, ~ guid, group = "xfilter"))
      )
    }
  )
)
```

````

**Comment by marcosnav** [comment]
@edavidaja that example works for me

Screen Shot 2021-06-04 at 15 27 17

Do you have an idea or noticed which component might be breaking?

**Comment by marcosnav** [comment]
@edavidaja any chance you have content that doesn't have a url? The only place where we use `.split` is when we try to generate image urls, however the babel parsed code might contain other `.split`s 🤷‍♂️

**Comment by marcosnav** [comment]
@edavidaja Found that I missed the card to accept crosstalk objects, although it doesn't have a reactive behavior, users might pass one to it and expect it to work. However, on the example you shared `rsc_card` is not in use 🤔

**Comment by edavidaja** [comment]
> @edavidaja any chance you have content that doesn't have a url? The only place where we use `.split` is when we try to generate image urls, however the babel parsed code might contain other `.split`s 🤷‍♂️

I'm running the example against dogfood, so the larger amount of content is probably causing the breakage for me.

> @edavidaja Found that I missed the card to accept crosstalk objects, although it doesn't have a reactive behavior, users might pass one to it and expect it to work. However, on the example you shared `rsc_card` is not in use 🤔

That's my fault--the card shouldn't have to take crosstalk objects since we don't expect it to be filtered; I should have cleaned up the labels in the example, which only uses the grid.

**Comment by edavidaja** [comment]
stopped randomly selecting rows 🤦🏾 , which is more clearly surfacing some issues:

- search and filter don't behave in grid view--if I search or filter on any tag in grid view, all items disappear and can't be reset to come back
- in table view, tag filtering doesn't work consistently--I should see kelly's examples if I select the audit tag, but I don't


````
---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
library(connectwidgets)
library(dplyr)
library(htmltools)
library(purrr)

knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)

client <- connect()

all_content <- client %>%
  content() %>% 
  filter(created_time >= "2020-10-05")
```

### xtalk

```{r card}
content_xfilter <- crosstalk::SharedData$new(
  all_content,
  group = "xfilter"
  )

rsc_content_shared <-
  all_content %>%
  group_nest(owner_username, .key = "content_df", keep = TRUE)

div(
  h3("Grouped Grids by Owner", class = "text-center"),
  bscols(rsc_search(content_xfilter), rsc_filter(content_xfilter)),
  pmap(
    rsc_content_shared,
    {
      ~ tagList(
        h4(..1),
        rsc_grid(crosstalk::SharedData$new(..2, group = "xfilter"))
      )
    }
  )
)
```


````

**Comment by marcosnav** [comment]
@edavidaja > stopped randomly selecting rows 🤦🏾 , which is more clearly surfacing some issues

I think that's happening because there are multiple `SharedData` objects with different data sets, but sharing the same group name `xfilter`. 

AFAIK, it is expected that shared data objects using the same group name or key, also use the same data set. Reactable and our new widgets communicate the indexes of rows/items to show/hide, so if the data sets are different those indexes won't match and that's why it breaks.

**Comment by edavidaja** [comment]
In the [grouping example in this crosstalk vignette](http://rstudio.github.io/crosstalk/using.html) there's an illustration of using groups to refer to subsets of the same data frame, which is what I'm trying to do by passing the overall data frame to the filter widget and then subsets to each card widget. I tried explicitly specifying the guids as keys, and that did not work at all.

**Comment by marcosnav** [comment]
@edavidaja That's interesting 🤔 

Anyway, reading through the example it says...
```
It’s critical that all SharedData instances in a group refer conceptually to the same data points, and share the same keys. This doesn’t mean that the data and keys need to be identical across SharedData instances in the group, but rather, that any overlapping key values must refer to the same data point or observation; and conversely, that related data points/observations in different SharedData instances must use identical keys.
```

So, yeah , I can see now why `Cannot read property 'split' of undefined` is showing up. I can fix that. Anyway, as said in crosstalk docs, when doing grouping, all elements should be grouped in a way that the indexes match for every subset and refer to the same data. So in our example of grouping by author, that won't happen since every author may have different content in different order.

**Comment by marcosnav** [comment]
Pushed a commit that fixes errors thrown when using subsets of data and filtering/searching selects items that do not exist on the grid view.

**Review by edavidaja — APPROVED** [review]
👍🏾 looks good!

**Pull request merged**
